Makefile: rework PGO flags
* Basically it's still the same '-fprofile-use' but without '-fprofile-values' and '-fvpt'.
  '-fprofile-values' and '-fvpt' must be enabled in gcov flags (but it will cause 'undefined reference to __gcov_time_profiler_counter' linking error).
* Remove flags that already enabled at '-O3'
* Bring back 'coverage-mismatch' warning

Signed-off-by: Diaz1401 <diaznura@outlook.com>