devfreq: bwmon: Export symbols
Export symbols to fix the following modpost errors:

  ERROR: "bw_hwmon_sample_end" [drivers/devfreq/bimc-bwmon.ko] undefined!
  ERROR: "register_bw_hwmon" [drivers/devfreq/bimc-bwmon.ko] undefined!
  ERROR: "update_bw_hwmon" [drivers/devfreq/bimc-bwmon.ko] undefined!

Change-Id: Ic0dedbad2f49e98b415a2ded471b2c35b97157a8
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
Signed-off-by: Diaz1401 <reagor8161@outlook.com>

Conflicts:
	drivers/devfreq/governor_bw_hwmon.c